{
 "title": "APM Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "region", "query": "regions()" },
   { "name": "compartment", "query": "compartments()" },
   {
    "name": "namespace",
    "query": "namespaces($region,$compartment)"
   },
   {
    "name": "resourcegroup",
    "query": "resourcegroups($region, $compartment, $namespace)"
   },
   {
    "name": "dimension",
    "query": "dimensions($region, $compartment, $namespace, $metric, $resourcegroup)"
   },
   {
    "name": "metric",
    "query": "metrics($region,$compartment, $namespace, $resourcegroup)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "    <h1>Application Performance Monitoring Dashboard Instructions</h1>\n    <p><a href=\"https://docs.oracle.com/en-us/iaas/application-performance-monitoring/home.htm\">Click here for APM Documentation</a></p>\n    <br>\n    <h2>How to use the Application Performance Monitoring Dashboard</h2>\n    <p>This dashboard provides examples that can be edited or duplicated to show <strong>APM </strong> metrices. </p>\n    <br>\n\n\n    <h3>Step-by-Step Instructions:</h3>\n    <ol>\n        <li>Choose a Region</li>\n        <li>Choose a Compartment</li>\n        <li>Enter <span style=\"color:red;\">namespace: oracle_apm_monitoring</span></li>\n        <li>No Resource Group required at present</li>\n        <li>Experiment with Dimensions, in most cases AppserverName, Hostname, AppserverType should work </li>\n    </ol>\n\n    <h3>Important Notes:</h3>\n    <ol>\n        <li>This dashboard is intended for use with the OCI APM services.</li>\n        <li>Please ensure that you have the necessary permissions and credentials to access the dashboard.</li>"
   }
  },
  {
   "title": "Uptime by Dimension",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [ "$dimension" ],
     "groupBy": "select option (optional)",
     "metric": "Uptime",
     "metricNames": [
      "BrowserAgentInjectionCount",
      "CircuitBreakerActivations",
      "DataQueueUsageMaxPercent",
      "DataRejectCount",
      "DataUploadTime",
      "DataUploaded",
      "ErrorCount",
      "ExporterQueueUsageMaxPercent",
      "SpanFinishCount",
      "SpanStartCount",
      "SpanTimedOutCount",
      "TotalSpanCount",
      "TotalSpanSampledCount",
      "TotalTraceCount",
      "TotalTraceSampledCount",
      "UploadCount",
      "UploadErrorCount"
     ],
     "namespace": "$namespace",
     "queryText": "Uptime[1m]{$dimension}.count()",
     "region": "$region",
     "resourcegroup": "NoResourceGroup",
     "statistic": "count()",
     "statisticLabel": "count",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Thread Waiting, Dead Lock Count ",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [ "$dimension" ],
     "groupBy": "select option (optional)",
     "intervalLabel": "1 minute",
     "legendFormat": "Thread Count ",
     "metric": "ThreadCount",
     "metricNames": [
      "BrowserAgentInjectionCount",
      "CircuitBreakerActivations",
      "DataQueueUsageMaxPercent",
      "DataRejectCount",
      "DataUploadTime",
      "DataUploaded",
      "ErrorCount",
      "ExporterQueueUsageMaxPercent",
      "SpanFinishCount",
      "SpanStartCount",
      "SpanTimedOutCount",
      "TotalSpanCount",
      "TotalSpanSampledCount",
      "TotalTraceCount",
      "TotalTraceSampledCount",
      "UploadCount",
      "UploadErrorCount"
     ],
     "namespace": "$namespace",
     "queryText": "ThreadCount[1m]{$dimension}.sum()",
     "region": "$region",
     "resourcegroup": "NoResourceGroup",
     "statistic": "sum()",
     "statisticLabel": "sum",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    },
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [ "$dimension" ],
     "groupBy": "select option (optional)",
     "intervalLabel": "1 minute",
     "legendFormat": "Thread Waiting Count",
     "metric": "ThreadWaitingCount",
     "metricNames": [
      "BrowserAgentInjectionCount",
      "CircuitBreakerActivations",
      "DataQueueUsageMaxPercent",
      "DataRejectCount",
      "DataUploadTime",
      "DataUploaded",
      "ErrorCount",
      "ExporterQueueUsageMaxPercent",
      "SpanFinishCount",
      "SpanStartCount",
      "SpanTimedOutCount",
      "TotalSpanCount",
      "TotalSpanSampledCount",
      "TotalTraceCount",
      "TotalTraceSampledCount",
      "UploadCount",
      "UploadErrorCount"
     ],
     "namespace": "$namespace",
     "queryText": "ThreadWaitingCount[1m]{$dimension}.avg()",
     "region": "$region",
     "resourcegroup": "NoResourceGroup",
     "statistic": "avg()",
     "statisticLabel": "average",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    },
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [ "$dimension" ],
     "groupBy": "select option (optional)",
     "intervalLabel": "1 minute",
     "legendFormat": "Thread Deadlock Count",
     "metric": "ThreadDeadlockCount",
     "metricNames": [
      "BrowserAgentInjectionCount",
      "CircuitBreakerActivations",
      "DataQueueUsageMaxPercent",
      "DataRejectCount",
      "DataUploadTime",
      "DataUploaded",
      "ErrorCount",
      "ExporterQueueUsageMaxPercent",
      "SpanFinishCount",
      "SpanStartCount",
      "SpanTimedOutCount",
      "TotalSpanCount",
      "TotalSpanSampledCount",
      "TotalTraceCount",
      "TotalTraceSampledCount",
      "UploadCount",
      "UploadErrorCount"
     ],
     "namespace": "$namespace",
     "queryText": "ThreadDeadlockCount[1m]{$dimension}.avg()",
     "region": "$region",
     "resourcegroup": "NoResourceGroup",
     "statistic": "avg()",
     "statisticLabel": "average",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "CPU process Load ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [ "$dimension" ],
     "groupBy": "select option (optional)",
     "metric": "ProcessCpuLoad",
     "metricNames": [
      "BrowserAgentInjectionCount",
      "CircuitBreakerActivations",
      "DataQueueUsageMaxPercent",
      "DataRejectCount",
      "DataUploadTime",
      "DataUploaded",
      "ErrorCount",
      "ExporterQueueUsageMaxPercent",
      "SpanFinishCount",
      "SpanStartCount",
      "SpanTimedOutCount",
      "TotalSpanCount",
      "TotalSpanSampledCount",
      "TotalTraceCount",
      "TotalTraceSampledCount",
      "UploadCount",
      "UploadErrorCount"
     ],
     "namespace": "$namespace",
     "queryText": "ProcessCpuLoad[1m]{$dimension}.avg()",
     "region": "$region",
     "resourcegroup": "NoResourceGroup",
     "statistic": "avg()",
     "statisticLabel": "average",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "CPU Process Time ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [ "$dimension" ],
     "groupBy": "select option (optional)",
     "intervalLabel": "1 minute",
     "legendFormat": "Hostname:  {{HostNames}}, Apllication:  {{AppserverType}} ",
     "metric": "ProcessCpuTime",
     "metricNames": [
      "BrowserAgentInjectionCount",
      "CircuitBreakerActivations",
      "DataQueueUsageMaxPercent",
      "DataRejectCount",
      "DataUploadTime",
      "DataUploaded",
      "ErrorCount",
      "ExporterQueueUsageMaxPercent",
      "SpanFinishCount",
      "SpanStartCount",
      "SpanTimedOutCount",
      "TotalSpanCount",
      "TotalSpanSampledCount",
      "TotalTraceCount",
      "TotalTraceSampledCount",
      "UploadCount",
      "UploadErrorCount"
     ],
     "namespace": "$namespace",
     "queryText": "ProcessCpuTime[1m]{$dimension}.increment()",
     "region": "$region",
     "resourcegroup": "NoResourceGroup",
     "statistic": "increment()",
     "statisticLabel": "per-interval change",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Heap Commited and Heap Used ",
   "type": "stat",
   "description": "This chart shows how much heap memory is committed versus how much is actually used over time. It helps in understanding the efficiency of memory usage and identifying potential memory issues.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [ "$dimension" ],
     "groupBy": "select option (optional)",
     "intervalLabel": "1 minute",
     "legendFormat": "Heap Committed  ",
     "metric": "HeapCommitted",
     "metricNames": [
      "BrowserAgentInjectionCount",
      "CircuitBreakerActivations",
      "DataQueueUsageMaxPercent",
      "DataRejectCount",
      "DataUploadTime",
      "DataUploaded",
      "ErrorCount",
      "ExporterQueueUsageMaxPercent",
      "SpanFinishCount",
      "SpanStartCount",
      "SpanTimedOutCount",
      "TotalSpanCount",
      "TotalSpanSampledCount",
      "TotalTraceCount",
      "TotalTraceSampledCount",
      "UploadCount",
      "UploadErrorCount"
     ],
     "namespace": "$namespace",
     "queryText": "HeapCommitted[1m]{$dimension}.avg()",
     "region": "$region",
     "resourcegroup": "NoResourceGroup",
     "statistic": "avg()",
     "statisticLabel": "average",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    },
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [ "$dimension" ],
     "groupBy": "select option (optional)",
     "intervalLabel": "1 minute",
     "legendFormat": "Heap Used ",
     "metric": "HeapUsed",
     "metricNames": [
      "BrowserAgentInjectionCount",
      "CircuitBreakerActivations",
      "DataQueueUsageMaxPercent",
      "DataRejectCount",
      "DataUploadTime",
      "DataUploaded",
      "ErrorCount",
      "ExporterQueueUsageMaxPercent",
      "SpanFinishCount",
      "SpanStartCount",
      "SpanTimedOutCount",
      "TotalSpanCount",
      "TotalSpanSampledCount",
      "TotalTraceCount",
      "TotalTraceSampledCount",
      "UploadCount",
      "UploadErrorCount"
     ],
     "namespace": "$namespace",
     "queryText": "HeapUsed[1m]{$dimension}.avg()",
     "region": "$region",
     "resourcegroup": "NoResourceGroup",
     "statistic": "avg()",
     "statisticLabel": "average",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Committed GC After Old v After Young  ",
   "type": "stat",
   "description": "Current committed memory for both old and young generations, which is useful for real-time monitoring.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [ "$dimension" ],
     "groupBy": "select option (optional)",
     "intervalLabel": "1 minute",
     "legendFormat": "Heap Commited After Old GC",
     "metric": "GcAfterOldCommitted",
     "metricNames": [
      "BrowserAgentInjectionCount",
      "CircuitBreakerActivations",
      "DataQueueUsageMaxPercent",
      "DataRejectCount",
      "DataUploadTime",
      "DataUploaded",
      "ErrorCount",
      "ExporterQueueUsageMaxPercent",
      "SpanFinishCount",
      "SpanStartCount",
      "SpanTimedOutCount",
      "TotalSpanCount",
      "TotalSpanSampledCount",
      "TotalTraceCount",
      "TotalTraceSampledCount",
      "UploadCount",
      "UploadErrorCount"
     ],
     "namespace": "$namespace",
     "queryText": "GcAfterOldCommitted[1m]{$dimension}.min()",
     "region": "$region",
     "resourcegroup": "NoResourceGroup",
     "statistic": "min()",
     "statisticLabel": "minimum",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    },
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [ "$dimension" ],
     "groupBy": "select option (optional)",
     "intervalLabel": "1 minute",
     "legendFormat": "Heap Commited After Young GC",
     "metric": "GcAfterYoungCommitted",
     "metricNames": [
      "BrowserAgentInjectionCount",
      "CircuitBreakerActivations",
      "DataQueueUsageMaxPercent",
      "DataRejectCount",
      "DataUploadTime",
      "DataUploaded",
      "ErrorCount",
      "ExporterQueueUsageMaxPercent",
      "SpanFinishCount",
      "SpanStartCount",
      "SpanTimedOutCount",
      "TotalSpanCount",
      "TotalSpanSampledCount",
      "TotalTraceCount",
      "TotalTraceSampledCount",
      "UploadCount",
      "UploadErrorCount"
     ],
     "namespace": "$namespace",
     "queryText": "GcAfterYoungCommitted[1m]{$dimension}.avg()",
     "region": "$region",
     "resourcegroup": "NoResourceGroup",
     "statistic": "avg()",
     "statisticLabel": "average",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Used GC After Old v After Young ",
   "type": "timeseries",
   "description": "Shows how much memory is being used after each GC event. A gradual increase in memory usage can indicate a memory leak.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [ "$dimension" ],
     "groupBy": "select option (optional)",
     "intervalLabel": "1 minute",
     "legendFormat": "GC After Old Used ",
     "metric": "GcAfterOldUsed",
     "metricNames": [
      "BrowserAgentInjectionCount",
      "CircuitBreakerActivations",
      "DataQueueUsageMaxPercent",
      "DataRejectCount",
      "DataUploadTime",
      "DataUploaded",
      "ErrorCount",
      "ExporterQueueUsageMaxPercent",
      "SpanFinishCount",
      "SpanStartCount",
      "SpanTimedOutCount",
      "TotalSpanCount",
      "TotalSpanSampledCount",
      "TotalTraceCount",
      "TotalTraceSampledCount",
      "UploadCount",
      "UploadErrorCount"
     ],
     "namespace": "$namespace",
     "queryText": "GcAfterOldUsed[1m]{$dimension}.avg()",
     "region": "$region",
     "resourcegroup": "NoResourceGroup",
     "statistic": "avg()",
     "statisticLabel": "average",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    },
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [ "$dimension" ],
     "groupBy": "select option (optional)",
     "intervalLabel": "1 minute",
     "legendFormat": "GC After Young Used ",
     "metric": "GcAfterYoungUsed",
     "metricNames": [
      "BrowserAgentInjectionCount",
      "CircuitBreakerActivations",
      "DataQueueUsageMaxPercent",
      "DataRejectCount",
      "DataUploadTime",
      "DataUploaded",
      "ErrorCount",
      "ExporterQueueUsageMaxPercent",
      "SpanFinishCount",
      "SpanStartCount",
      "SpanTimedOutCount",
      "TotalSpanCount",
      "TotalSpanSampledCount",
      "TotalTraceCount",
      "TotalTraceSampledCount",
      "UploadCount",
      "UploadErrorCount"
     ],
     "namespace": "$namespace",
     "queryText": "GcAfterYoungUsed[1m]{$dimension}.avg()",
     "region": "$region",
     "resourcegroup": "NoResourceGroup",
     "statistic": "avg()",
     "statisticLabel": "average",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Total Time GC Young v Old Total ",
   "type": "timeseries",
   "description": "Track how often garbage collection is happening (both young and old generations) Track how much time is being spent on garbage collection (both young and old generations). Long GC times can indicate performance issues.\n",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [ "$dimension" ],
     "groupBy": "select option (optional)",
     "intervalLabel": "1 minute",
     "legendFormat": "GC Young Total  ",
     "metric": "GcYoungTotalTime",
     "metricNames": [
      "BrowserAgentInjectionCount",
      "CircuitBreakerActivations",
      "DataQueueUsageMaxPercent",
      "DataRejectCount",
      "DataUploadTime",
      "DataUploaded",
      "ErrorCount",
      "ExporterQueueUsageMaxPercent",
      "SpanFinishCount",
      "SpanStartCount",
      "SpanTimedOutCount",
      "TotalSpanCount",
      "TotalSpanSampledCount",
      "TotalTraceCount",
      "TotalTraceSampledCount",
      "UploadCount",
      "UploadErrorCount"
     ],
     "namespace": "$namespace",
     "queryText": "GcYoungTotalTime[1m]{$dimension}.avg()",
     "region": "$region",
     "resourcegroup": "NoResourceGroup",
     "statistic": "avg()",
     "statisticLabel": "average",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    },
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [ "$dimension" ],
     "groupBy": "select option (optional)",
     "intervalLabel": "1 minute",
     "legendFormat": "GC Old Total ",
     "metric": "GcOldTotalTime",
     "metricNames": [
      "BrowserAgentInjectionCount",
      "CircuitBreakerActivations",
      "DataQueueUsageMaxPercent",
      "DataRejectCount",
      "DataUploadTime",
      "DataUploaded",
      "ErrorCount",
      "ExporterQueueUsageMaxPercent",
      "SpanFinishCount",
      "SpanStartCount",
      "SpanTimedOutCount",
      "TotalSpanCount",
      "TotalSpanSampledCount",
      "TotalTraceCount",
      "TotalTraceSampledCount",
      "UploadCount",
      "UploadErrorCount"
     ],
     "namespace": "$namespace",
     "queryText": "GcOldTotalTime[1m]{$dimension}.avg()",
     "region": "$region",
     "resourcegroup": "NoResourceGroup",
     "statistic": "avg()",
     "statisticLabel": "average",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  }
 ]
}