{
 "title": "Database-Management",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "region", "query": "regions()" },
   { "name": "compartment", "query": "compartments()" },
   {
    "name": "namespace",
    "query": "namespaces($region,$compartment)"
   },
   {
    "name": "resourcegroup",
    "query": "resourcegroups($region, $compartment, $namespace)"
   },
   {
    "name": "dimension",
    "query": "dimensions($region, $compartment, $namespace, $metric, $resourcegroup)"
   },
   {
    "name": "metric",
    "query": "metrics($region,$compartment, $namespace, $resourcegroup)"
   }
  ]
 },
 "panels": [
  {
   "title": "Instructions",
   "type": "text",
   "gridPos": { "h": 13, "w": 16, "x": 5, "y": 0 },
   "options": {
    "content": "   <h1>Database Management Dashboard Instructions</h1>\n    <p><a href=\"https://docs.oracle.com/en-us/iaas/database-management/home.htm\">Click here for Database Management Documentation</a></p>\n    <br>\n    <h2>How to use the Database Management  Dashboard</h2>\n    <p>This dashboard provides examples that can be edited or duplicated to show <strong>Database Management</strong> metrices. </p>\n    <br>\n\n\n    <h3>Step-by-Step Instructions:</h3>\n    <ol>\n        <li>Choose a Region</li>\n        <li>Choose a Compartment</li>\n        <li>Enter <span style=\"color:red;\">namespace: oracle_oci_database</span></li>\n        <li>No Resource Groupis required at the moment</li>\n        <li>Experiment with Dimensions, in most cases resourceName , hostName, deploymentType should work </li>\n    </ol>\n\n    <h3>Important Notes:</h3>\n    <ol>\n        <li>This dashboard is intended for use with the OCI Database Manaement Services.</li>\n        <li>Please ensure that you have the necessary permissions and credentials to access the dashboard.</li>\n"
   }
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [ "$dimension" ],
     "groupBy": "select option (optional)",
     "legendFormat": "{{resourceName}}",
     "metric": "MonitoringStatus",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "MonitoringStatus[1m]{$dimension}.avg()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "avg()",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "CPU Count ",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [ "$dimension" ],
     "groupBy": "select option (optional)",
     "legendFormat": "{{hostName}} ",
     "metric": "CpuCount",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "CpuCount[1m]{$dimension}.avg()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "avg()",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "CPU Utilisation ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [ "$dimension" ],
     "groupBy": "select option (optional)",
     "legendFormat": "{{hostName}} ",
     "metric": "CpuUtilization",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "CpuUtilization[1m]{$dimension}.avg()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "avg()",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "PGA and SGA Memory Usage ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [
      "memoryType=\"PGA\"",
      "$dimension"
     ],
     "groupBy": "select option (optional)",
     "legendFormat": "{{resourceName}} {{memoryType}}",
     "metric": "MemoryUsage",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "MemoryUsage[1m]{memoryType=\"PGA\",$dimension}.sum()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "sum()",
     "statisticLabel": "sum",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    },
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [
      "memoryType=\"SGA\"",
      "$dimension"
     ],
     "groupBy": "select option (optional)",
     "legendFormat": "{{resourceName}} SGA",
     "metric": "MemoryUsage",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "MemoryUsage[1m]{memoryType=\"SGA\",$dimension}.avg()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "avg()",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Storage Utilisation per day",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [ "$dimension" ],
     "groupBy": "select option (optional)",
     "intervalLabel": "1 day",
     "legendFormat": "{{resourceName}}",
     "metric": "StorageUtilization",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "StorageUtilization[1d]{$dimension}.avg()",
     "queryTextRaw": "StorageUtilization[240m].mean()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "avg()",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Storage Allocated per day",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [ "$dimension" ],
     "groupBy": "select option (optional)",
     "intervalLabel": "1 day",
     "legendFormat": "{{resourceName}} ",
     "metric": "StorageAllocated",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "StorageAllocated[1d]{$dimension}.sum()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "sum()",
     "statisticLabel": "sum",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Storage Used per day",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [ "$dimension" ],
     "groupBy": "select option (optional)",
     "intervalLabel": "1 day",
     "legendFormat": "{{resourceName}} ",
     "metric": "StorageUsed",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "StorageUsed[1d]{$dimension}.sum()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "sum()",
     "statisticLabel": "sum",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Storage Used By TableSpace every 5hrs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [ "$dimension" ],
     "groupBy": "select option (optional)",
     "legendFormat": "{{hostName}}",
     "metric": "CpuUtilization",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "StorageUsedByTablespace[240m].groupBy(tablespaceName).mean()",
     "queryTextRaw": "StorageUsedByTablespace[240m].groupBy(tablespaceName).mean()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "avg()",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  }
 ]
}