{
 "title": "Stack-Monitoring",
 "description": "namspac - oracle_appmgmt",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "region", "query": "regions()" },
   { "name": "compartment", "query": "compartments()" },
   {
    "name": "namespace",
    "query": "namespaces($region,$compartment)"
   },
   {
    "name": "resourcegroup",
    "query": "resourcegroups($region, $compartment, $namespace)"
   },
   {
    "name": "dimension",
    "query": "dimensions($region, $compartment, $namespace, $metric, $resourcegroup)"
   },
   {
    "name": "metric",
    "query": "metrics($region,$compartment, $namespace, $resourcegroup)"
   }
  ]
 },
 "panels": [
  {
   "title": "Status 12",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [ "$dimension" ],
     "groupBy": "select option (optional)",
     "intervalLabel": "1 minute",
     "legendFormat": "{{resourceName}}",
     "metric": "MonitoringStatus",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "MonitoringStatus[1m]{$dimension}.count()",
     "region": "us-ashburn-1",
     "resourcegroup": "$resourcegroup",
     "statistic": "count()",
     "statisticLabel": "count",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Root (/) Filesystem Utilisation",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [
      "$dimension",
      "fileSystemName=\"/\""
     ],
     "groupBy": "select option (optional)",
     "legendFormat": "root (/) {{resourceName}}",
     "metric": "FilesystemUtilization",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "FilesystemUtilization[1m]{$dimension,fileSystemName=\"/\"}.avg()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "avg()",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Host CPU Utilisation - System and User",
   "type": "timeseries",
   "description": "Showing User and System CPU Utilisation with a maximum threshold of 80%",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [
      "Type=\"System\"",
      "$dimension"
     ],
     "groupBy": "select option (optional)",
     "intervalLabel": "1 minute",
     "legendFormat": "{{resourceName}} System CPU",
     "metric": "CPUUtilization",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "CPUUtilization[1m]{Type=\"System\",$dimension}.avg()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "avg()",
     "statisticLabel": "average",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    },
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [
      "Type=\"User\"",
      "$dimension"
     ],
     "groupBy": "select option (optional)",
     "legendFormat": "User CPU",
     "metric": "CpuUtilization",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "CpuUtilization[1m]{Type=\"User\",$dimension}.avg()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "avg()",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Host CPU Utilisation - Total and Idle",
   "type": "timeseries",
   "description": "Showing Idle and Total CPU Utilisation with a maximum threshold of 80%",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [
      "Type=\"Idle\"",
      "$dimension"
     ],
     "groupBy": "select option (optional)",
     "intervalLabel": "1 minute",
     "legendFormat": "{{resourceName}} Idle CPU",
     "metric": "CPUUtilization",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "CPUUtilization[1m]{Type=\"Idle\",$dimension}.avg()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "avg()",
     "statisticLabel": "average",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    },
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [
      "Type=\"Total\"",
      "$dimension"
     ],
     "groupBy": "select option (optional)",
     "legendFormat": "Total CPU",
     "metric": "CpuUtilization",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "CpuUtilization[1m]{Type=\"Total\",$dimension}.avg()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "avg()",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Total Network Activity Summary",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [
      "Type=\"Total\"",
      "$dimension"
     ],
     "groupBy": "select option (optional)",
     "legendFormat": "{{resourceName}}",
     "metric": "NetworkActivitySummary",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "NetworkActivitySummary[1m]{Type=\"Total\",$dimension}.max()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "max()",
     "statisticLabel": "maximum",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Total and Logical Host Memory Utilisation ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [
      "Type=\"Total\"",
      "$dimension"
     ],
     "groupBy": "select option (optional)",
     "legendFormat": "{{resourceName}} - Total Memory",
     "metric": "MemoryUtilization",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "MemoryUtilization[1m]{Type=\"Total\",$dimension}.avg()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "avg()",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    },
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [
      "Type=\"Logical\"",
      "$dimension"
     ],
     "groupBy": "select option (optional)",
     "legendFormat": "{{resourceName}} - Logical Memory",
     "metric": "MemoryUtilization",
     "metricNames": [
      "CpuLoad",
      "CpuUsage",
      "CpuUtilization",
      "DiskActivitySummary",
      "FilesystemUsage",
      "FilesystemUtilization",
      "InodeUsage",
      "InodeUtilization",
      "MemoryUsed",
      "MemoryUtilization",
      "MonitoringStatus",
      "NetworkActivitySummary",
      "PagingActivity",
      "SwapUsage",
      "SwapUtilization",
      "TopProcessesCpuUsage",
      "TopProcessesCpuUtilization",
      "TopProcessesElapsedTime",
      "TopProcessesMemoryUtilization",
      "TopProcessesPhysicalMemoryUsage",
      "TopProcessesVirtualMemoryUsage"
     ],
     "namespace": "$namespace",
     "queryText": "MemoryUtilization[1m]{Type=\"Logical\",$dimension}.avg()",
     "region": "$region",
     "resourcegroup": "host",
     "statistic": "avg()",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Free and Used Swap Utilisation",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [
      "Type=\"Free\"",
      "$dimension"
     ],
     "groupBy": "select option (optional)",
     "legendFormat": "{{resourceName}} - Free Memory",
     "metric": "SwapUtilization",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "SwapUtilization[1m]{Type=\"Free\",$dimension}.avg()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "avg()",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    },
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [
      "Type=\"Used\"",
      "$dimension"
     ],
     "groupBy": "select option (optional)",
     "legendFormat": "{{resourceName}} - Used Memory",
     "metric": "SwapUtilization",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "SwapUtilization[1m]{Type=\"Used\",$dimension}.avg()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "avg()",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  }
 ]
}