{
 "title": "Stack-Monitoring",
 "description": "namspace - oracle_appmgmt",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "region", "query": "regions()" },
   { "name": "compartment", "query": "compartments()" },
   {
    "name": "namespace",
    "query": "namespaces($region,$compartment)"
   },
   {
    "name": "resourcegroup",
    "query": "resourcegroups($region, $compartment, $namespace)"
   },
   {
    "name": "dimension",
    "query": "dimensions($region, $compartment, $namespace, $metric, $resourcegroup)"
   },
   {
    "name": "metric",
    "query": "metrics($region,$compartment, $namespace, $resourcegroup)"
   }
  ]
 },
 "panels": [
  {
   "title": "Instructions",
   "type": "text",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "   <h1>Stack Monitoring Dashboard Instructions</h1>\n    <p><a href=\"https://docs.oracle.com/en-us/iaas/stack-monitoring/index.html\">Click here for Stack Monitoring Documentation</a></p>\n    <br>\n    <h2>How to use the Stack Monitoring Dashboard</h2>\n    <p>This dashboard provides examples that can be edited or duplicated to show <strong>Stack Monitoring </strong> metrices. </p>\n    <br>\n\n\n    <h3>Step-by-Step Instructions:</h3>\n    <ol>\n        <li>Choose a Region</li>\n        <li>Choose a Compartment</li>\n        <li>Enter <span style=\"color:red;\">namespace: oracle_appmgmt</span></li>\n        <li>Select host for  Resource Group</li>\n        <li>Experiment with Dimensions, in most cases resourceName , hostType, osType should work </li>\n    </ol>\n\n    <h3>Important Notes:</h3>\n    <ol>\n        <li>This dashboard is intended for use with the OCI Stack Monitoring services.</li>\n        <li>Please ensure that you have the necessary permissions and credentials to access the dashboard.</li>"
   }
  },
  {
   "title": "Status ",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [ "$dimension" ],
     "groupBy": "select option (optional)",
     "intervalLabel": "1 minute",
     "legendFormat": "{{resourceName}}",
     "metric": "MonitoringStatus",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "MonitoringStatus[1m]{$dimension}.count()",
     "region": "us-ashburn-1",
     "resourcegroup": "$resourcegroup",
     "statistic": "count()",
     "statisticLabel": "count",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Root (/) Filesystem Utilisation",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [
      "$dimension",
      "fileSystemName=\"/\""
     ],
     "groupBy": "select option (optional)",
     "legendFormat": "root (/) {{resourceName}}",
     "metric": "FilesystemUtilization",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "FilesystemUtilization[1m]{$dimension,fileSystemName=\"/\"}.avg()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "avg()",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "CPU Utilisation - System and User",
   "type": "timeseries",
   "description": "Showing User and System CPU Utilisation with a maximum threshold of 80%",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [
      "Type=\"System\"",
      "$dimension"
     ],
     "groupBy": "select option (optional)",
     "intervalLabel": "1 minute",
     "legendFormat": "{{resourceName}} System CPU",
     "metric": "CPUUtilization",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "CPUUtilization[1m]{Type=\"System\",$dimension}.avg()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "avg()",
     "statisticLabel": "average",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    },
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [
      "Type=\"User\"",
      "$dimension"
     ],
     "groupBy": "select option (optional)",
     "legendFormat": "User CPU",
     "metric": "CpuUtilization",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "CpuUtilization[1m]{Type=\"User\",$dimension}.avg()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "avg()",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "CPU Utilisation - Total and Idle",
   "type": "timeseries",
   "description": "Showing Idle and Total CPU Utilisation with a maximum threshold of 80%",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [
      "Type=\"Idle\"",
      "$dimension"
     ],
     "groupBy": "select option (optional)",
     "intervalLabel": "1 minute",
     "legendFormat": "{{resourceName}} Idle CPU",
     "metric": "CPUUtilization",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "CPUUtilization[1m]{Type=\"Idle\",$dimension}.avg()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "avg()",
     "statisticLabel": "average",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    },
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [
      "Type=\"Total\"",
      "$dimension"
     ],
     "groupBy": "select option (optional)",
     "legendFormat": "Total CPU",
     "metric": "CpuUtilization",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "CpuUtilization[1m]{Type=\"Total\",$dimension}.avg()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "avg()",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "CPU Load -Every 15mins",
   "type": "timeseries",
   "description": "Showing Idle and Total CPU Utilisation with a maximum threshold of 80%",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "count" } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [
      "$dimension",
      "LoadInterval=\"5minutes\""
     ],
     "groupBy": "select option (optional)",
     "intervalLabel": "1 minute",
     "legendFormat": "{{resourceName}}",
     "metric": "CpuLoad",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "CpuLoad[1m]{$dimension,LoadInterval=\"5minutes\"}.avg()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "avg()",
     "statisticLabel": "average",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Total Network Activity Summary",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [
      "Type=\"Total\"",
      "$dimension"
     ],
     "groupBy": "select option (optional)",
     "legendFormat": "{{resourceName}}",
     "metric": "NetworkActivitySummary",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "NetworkActivitySummary[1m]{Type=\"Total\",$dimension}.max()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "max()",
     "statisticLabel": "maximum",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Total and Logical Host Memory Utilisation ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [
      "Type=\"Total\"",
      "$dimension"
     ],
     "groupBy": "select option (optional)",
     "legendFormat": "{{resourceName}} - Total Memory",
     "metric": "MemoryUtilization",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "MemoryUtilization[1m]{Type=\"Total\",$dimension}.avg()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "avg()",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    },
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [
      "Type=\"Logical\"",
      "$dimension"
     ],
     "groupBy": "select option (optional)",
     "legendFormat": "{{resourceName}} - Logical Memory",
     "metric": "MemoryUtilization",
     "metricNames": [
      "CpuLoad",
      "CpuUsage",
      "CpuUtilization",
      "DiskActivitySummary",
      "FilesystemUsage",
      "FilesystemUtilization",
      "InodeUsage",
      "InodeUtilization",
      "MemoryUsed",
      "MemoryUtilization",
      "MonitoringStatus",
      "NetworkActivitySummary",
      "PagingActivity",
      "SwapUsage",
      "SwapUtilization",
      "TopProcessesCpuUsage",
      "TopProcessesCpuUtilization",
      "TopProcessesElapsedTime",
      "TopProcessesMemoryUtilization",
      "TopProcessesPhysicalMemoryUsage",
      "TopProcessesVirtualMemoryUsage"
     ],
     "namespace": "$namespace",
     "queryText": "MemoryUtilization[1m]{Type=\"Logical\",$dimension}.avg()",
     "region": "$region",
     "resourcegroup": "host",
     "statistic": "avg()",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Total Disk Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [
      "Type=\"Total\"",
      "$dimension"
     ],
     "groupBy": "select option (optional)",
     "legendFormat": "{{resourceName}} {{diskName}}",
     "metric": "DiskActivitySummary",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "DiskActivitySummary[1m]{Type=\"Total\",$dimension}.max()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "max()",
     "statisticLabel": "maximum",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Free and Used Swap Utilisation",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [
      "Type=\"Free\"",
      "$dimension"
     ],
     "groupBy": "select option (optional)",
     "legendFormat": "{{resourceName}} - Free Memory",
     "metric": "SwapUtilization",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "SwapUtilization[1m]{Type=\"Free\",$dimension}.avg()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "avg()",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    },
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [
      "Type=\"Used\"",
      "$dimension"
     ],
     "groupBy": "select option (optional)",
     "legendFormat": "{{resourceName}} - Used Memory",
     "metric": "SwapUtilization",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "SwapUtilization[1m]{Type=\"Used\",$dimension}.avg()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "avg()",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  }
 ]
}