{
 "title": "OPSI2",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "region", "query": "regions()" },
   { "name": "compartment", "query": "compartments()" },
   {
    "name": "namespace",
    "query": "namespaces($region,$compartment)"
   },
   {
    "name": "resourcegroup",
    "query": "resourcegroups($region, $compartment, $namespace)"
   },
   {
    "name": "dimension",
    "query": "dimensions($region, $compartment, $namespace, $metric, $resourcegroup)"
   },
   {
    "name": "metric",
    "query": "metrics($region,$compartment, $namespace, $resourcegroup)"
   },
   {
    "name": "hostResourceMetric",
    "query": "CPU : CPU, Memory : LOGICAL_MEMORY,Storage : STORAGE"
   },
   {
    "name": "resourceType",
    "query": "Hosts : EXTERNAL-HOST, Databases : EXTERNAL-PDB"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 0 },
   "options": {
    "content": "\n\n    <h1>OPSI Insights Dashboard Instructions</h1>\n    <p><a href=\"https://docs.public.oneportal.content.oci.oraclecloud.com/en-us/iaas/operations-insights/home.htm\">Click here for OPSI Documentation</a></p>\n    <h2>How to use the Opsi Insights Dashboard</h2>\n    <p>This dashboard provides examples that can be edited or duplicated to show <strong>High</strong> and <strong>Low</strong> utilization of some metrics for Hosts and Databasees.</p>\n\n    <h3>Step-by-Step Instructions:</h3>\n    <ol>\n        <li>Select Region</li>\n        <li>Select Compartment</li>\n        <li>Enter <span style=\"color:red;\">namespace: oci_operational_insights</span></li>\n        <li>No resourcegroup is required</li>\n    </ol>\n\n    <h3>Important Notes:</h3>\n    <ol>\n        <li>This dashboard is intended for use with the OCI Operational Insights service.</li>\n        <li>Please ensure that you have the necessary permissions and credentials to access the dashboard.</li>\n    </ol>\n\n\n"
   }
  },
  {
   "title": "${resourceType:text} Insights",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "repeat": "resourceType",
   "collapsed": true,
   "panels": [
    {
     "title": "Number of ${resourceType:text} Reaching or Reached High ${hostResourceMetric:text} Utilisation in the next 30 Days",
     "type": "stat",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "Hosts" } },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "compartment": "$compartment",
       "compartmentName": "$compartment",
       "groupBy": "select option (optional)",
       "legendFormat": "{{resourceDisplayName}}",
       "metric": "select metric",
       "metricNames": "$resourcegroup",
       "metricNamesFromNS": "$namespace",
       "namespace": "$namespace",
       "queryText": "DaysToReachHighUtilization[1d]{resourceMetric =~ \"$hostResourceMetric\", resourceType =~ \"${resourceType}\"}.avg()",
       "queryTextRaw": "DaysToReachHighUtilization[1d]{resourceMetric =~ \"$hostResourceMetric\", resourceType =~ \"${resourceType}\"}.avg()",
       "region": "$region",
       "resourcegroup": "$resourcegroup",
       "statistic": "select aggregation",
       "tenancy": "DEFAULT/",
       "tenancyName": "DEFAULT/"
      }
     ]
    },
    {
     "title": "Top 5 ${resourceType:text} Reaching or Reached High ${hostResourceMetric:text} Utilisation",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 7, "x": 10, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "d" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "compartment": "$compartment",
       "compartmentName": "$compartment",
       "groupBy": "select option (optional)",
       "legendFormat": "{{resourceDisplayName}}",
       "metric": "select metric",
       "metricNames": "$resourcegroup",
       "metricNamesFromNS": "$namespace",
       "namespace": "$namespace",
       "queryText": "DaysToReachHighUtilization[1d]{resourceMetric =~ \"$hostResourceMetric\", resourceType =~ \"${resourceType}\"}.avg()",
       "queryTextRaw": "DaysToReachHighUtilization[1d]{resourceMetric =~ \"$hostResourceMetric\", resourceType =~ \"${resourceType}\"}.avg()",
       "region": "$region",
       "resourcegroup": "$resourcegroup",
       "statistic": "select aggregation",
       "tenancy": "DEFAULT/",
       "tenancyName": "DEFAULT/"
      }
     ]
    },
    {
     "title": "All ${resourceType:text} Reaching or Reached High ${hostResourceMetric:text} Utilisation",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "d" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "compartment": "$compartment",
       "compartmentName": "$compartment",
       "groupBy": "select option (optional)",
       "legendFormat": "{{resourceDisplayName}}",
       "metric": "select metric",
       "metricNames": "$resourcegroup",
       "namespace": "$namespace",
       "queryText": "DaysToReachHighUtilization[1d]{resourceMetric =~ \"$hostResourceMetric\", resourceType =~ \"${resourceType}\"}.avg()",
       "queryTextRaw": "DaysToReachHighUtilization[1d]{resourceMetric =~ \"$hostResourceMetric\", resourceType =~ \"${resourceType}\"}.avg()",
       "region": "$region",
       "resourcegroup": "$resourcegroup",
       "statistic": "select aggregation",
       "tenancy": "DEFAULT/",
       "tenancyName": "DEFAULT/"
      }
     ]
    },
    {
     "title": "Number of ${resourceType:text} Reaching or Reached Low ${hostResourceMetric:text} Utilisation in the next 30 Days",
     "type": "stat",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "Hosts" } },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "compartment": "$compartment",
       "compartmentName": "$compartment",
       "groupBy": "select option (optional)",
       "legendFormat": "{{resourceDisplayName}}",
       "metric": "select metric",
       "metricNames": "$resourcegroup",
       "metricNamesFromNS": "$namespace",
       "namespace": "$namespace",
       "queryText": "DaysToReachLowUtilization[1d]{resourceMetric =~ \"$hostResourceMetric\", resourceType =~ \"${resourceType}\"}.avg()",
       "queryTextRaw": "DaysToReachLowUtilization[1d]{resourceMetric =~ \"$hostResourceMetric\", resourceType =~ \"${resourceType}\"}.avg()",
       "region": "$region",
       "resourcegroup": "$resourcegroup",
       "statistic": "select aggregation",
       "tenancy": "DEFAULT/",
       "tenancyName": "DEFAULT/"
      }
     ]
    },
    {
     "title": "Top 5 ${resourceType:text} Reaching or Reached Low ${hostResourceMetric:text} Utilisation",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 7, "x": 10, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "d" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "compartment": "$compartment",
       "compartmentName": "$compartment",
       "groupBy": "select option (optional)",
       "legendFormat": "{{resourceDisplayName}}",
       "metric": "select metric",
       "metricNames": "$resourcegroup",
       "metricNamesFromNS": "$namespace",
       "namespace": "$namespace",
       "queryText": "DaysToReachLowUtilization[1d]{resourceMetric =~ \"$hostResourceMetric\", resourceType =~ \"${resourceType}\"}.avg()",
       "queryTextRaw": "DaysToReachLowUtilization[1d]{resourceMetric =~ \"$hostResourceMetric\", resourceType =~ \"${resourceType}\"}.avg()",
       "region": "$region",
       "resourcegroup": "$resourcegroup",
       "statistic": "select aggregation",
       "tenancy": "DEFAULT/",
       "tenancyName": "DEFAULT/"
      }
     ]
    },
    {
     "title": "All ${resourceType:text} Reaching or Reached Low ${hostResourceMetric:text} Utilisation",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "d" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "compartment": "$compartment",
       "compartmentName": "$compartment",
       "groupBy": "select option (optional)",
       "legendFormat": "{{resourceDisplayName}}",
       "metric": "select metric",
       "metricNames": "$resourcegroup",
       "namespace": "$namespace",
       "queryText": "DaysToReachLowUtilization[1d]{resourceMetric =~ \"$hostResourceMetric\", resourceType =~ \"${resourceType}\"}.avg()",
       "queryTextRaw": "DaysToReachLowUtilization[1d]{resourceMetric =~ \"$hostResourceMetric\", resourceType =~ \"${resourceType}\"}.avg()",
       "region": "$region",
       "resourcegroup": "$resourcegroup",
       "statistic": "select aggregation",
       "tenancy": "DEFAULT/",
       "tenancyName": "DEFAULT/"
      }
     ]
    }
   ]
  },
  {
   "title": "Database Insights",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of DBs to Reaching or Reached High ${hostResourceMetric:text} Utilisation in the next 30 Days",
     "type": "stat",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "DBs" } },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "compartment": "$compartment",
       "compartmentName": "$compartment",
       "groupBy": "select option (optional)",
       "legendFormat": "{{resourceDisplayName}}",
       "metric": "select metric",
       "metricNames": "$resourcegroup",
       "metricNamesFromNS": "$namespace",
       "namespace": "$namespace",
       "queryText": "DaysToReachHighUtilization[1d]{resourceMetric =~ \"CPU\", resourceType =~ \"EXTERNAL-PDB\"}.avg()  ",
       "queryTextRaw": "DaysToReachHighUtilization[1d]{resourceMetric =~ \"CPU\", resourceType =~ \"EXTERNAL-PDB\"}.avg()  ",
       "region": "$region",
       "resourcegroup": "$resourcegroup",
       "statistic": "select aggregation",
       "tenancy": "DEFAULT/",
       "tenancyName": "DEFAULT/"
      },
      {
       "compartment": "$compartment",
       "compartmentName": "$compartment",
       "groupBy": "select option (optional)",
       "legendFormat": "{{resourceDisplayName}}",
       "metric": "select metric",
       "metricNames": "$resourcegroup",
       "metricNamesFromNS": "$namespace",
       "namespace": "$namespace",
       "queryText": "DaysToReachHighUtilization[1d]{resourceMetric =~ \"CPU\", resourceType =~ \"COMANAGED-VM-PDB\"}.avg() ",
       "queryTextRaw": "DaysToReachHighUtilization[1d]{resourceMetric =~ \"CPU\", resourceType =~ \"COMANAGED-VM-PDB\"}.avg() ",
       "region": "$region",
       "resourcegroup": "$resourcegroup",
       "statistic": "select aggregation",
       "tenancy": "DEFAULT/",
       "tenancyName": "DEFAULT/"
      },
      {
       "compartment": "$compartment",
       "compartmentName": "$compartment",
       "groupBy": "select option (optional)",
       "legendFormat": "{{resourceDisplayName}}",
       "metric": "select metric",
       "metricNames": "$resourcegroup",
       "metricNamesFromNS": "$namespace",
       "namespace": "$namespace",
       "queryText": "DaysToReachHighUtilization[1d]{resourceMetric =~ \"CPU\", resourceType =~ \"EXTERNAL-NONCDB\"}.avg() ",
       "queryTextRaw": "DaysToReachHighUtilization[1d]{resourceMetric =~ \"CPU\", resourceType =~ \"EXTERNAL-NONCDB\"}.avg() ",
       "region": "$region",
       "resourcegroup": "$resourcegroup",
       "statistic": "select aggregation",
       "tenancy": "DEFAULT/",
       "tenancyName": "DEFAULT/"
      }
     ]
    },
    {
     "title": "Top 5 Databases Reaching or Reached High ${hostResourceMetric:text} Utilisation",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 7, "x": 10, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "d" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "compartment": "$compartment",
       "compartmentName": "$compartment",
       "groupBy": "select option (optional)",
       "legendFormat": "{{resourceDisplayName}}",
       "metric": "select metric",
       "metricNames": "$resourcegroup",
       "metricNamesFromNS": "$namespace",
       "namespace": "$namespace",
       "queryText": "DaysToReachHighUtilization[1d]{resourceMetric =~ \"CPU\", resourceType =~ \"EXTERNAL-PDB\"}.avg() ",
       "queryTextRaw": "DaysToReachHighUtilization[1d]{resourceMetric =~ \"CPU\", resourceType =~ \"EXTERNAL-PDB\"}.avg() ",
       "region": "$region",
       "resourcegroup": "$resourcegroup",
       "statistic": "select aggregation",
       "tenancy": "DEFAULT/",
       "tenancyName": "DEFAULT/"
      },
      {
       "compartment": "$compartment",
       "compartmentName": "$compartment",
       "groupBy": "select option (optional)",
       "legendFormat": "{{resourceDisplayName}}",
       "metric": "select metric",
       "metricNames": "$resourcegroup",
       "metricNamesFromNS": "$namespace",
       "namespace": "$namespace",
       "queryText": "DaysToReachHighUtilization[1d]{resourceMetric =~ \"CPU\", resourceType =~ \"COMANAGED-VM-PDB\"}.avg() ",
       "queryTextRaw": "DaysToReachHighUtilization[1d]{resourceMetric =~ \"CPU\", resourceType =~ \"COMANAGED-VM-PDB\"}.avg() ",
       "region": "$region",
       "resourcegroup": "$resourcegroup",
       "statistic": "select aggregation",
       "tenancy": "DEFAULT/",
       "tenancyName": "DEFAULT/"
      },
      {
       "compartment": "$compartment",
       "compartmentName": "$compartment",
       "groupBy": "select option (optional)",
       "legendFormat": "{{resourceDisplayName}}",
       "metric": "select metric",
       "metricNames": "$resourcegroup",
       "metricNamesFromNS": "$namespace",
       "namespace": "$namespace",
       "queryText": "DaysToReachHighUtilization[1d]{resourceMetric =~ \"CPU\", resourceType =~ \"EXTERNAL-NONCDB\"}.avg() ",
       "queryTextRaw": "DaysToReachHighUtilization[1d]{resourceMetric =~ \"CPU\", resourceType =~ \"EXTERNAL-NONCDB\"}.avg() ",
       "region": "$region",
       "resourcegroup": "$resourcegroup",
       "statistic": "select aggregation",
       "tenancy": "DEFAULT/",
       "tenancyName": "DEFAULT/"
      }
     ]
    },
    {
     "title": "All Databases Reaching or Reached High ${hostResourceMetric:text} Utilisation",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "d" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "compartment": "$compartment",
       "compartmentName": "$compartment",
       "groupBy": "select option (optional)",
       "legendFormat": "{{resourceDisplayName}}",
       "metric": "select metric",
       "metricNames": "$resourcegroup",
       "namespace": "$namespace",
       "queryText": "DaysToReachHighUtilization[1d]{resourceMetric =~ \"CPU\", resourceType =~ \"EXTERNAL-PDB\"}.avg() ",
       "queryTextRaw": "DaysToReachHighUtilization[1d]{resourceMetric =~ \"CPU\", resourceType =~ \"EXTERNAL-PDB\"}.avg() ",
       "region": "$region",
       "resourcegroup": "$resourcegroup",
       "statistic": "select aggregation",
       "tenancy": "DEFAULT/",
       "tenancyName": "DEFAULT/"
      },
      {
       "compartment": "$compartment",
       "compartmentName": "$compartment",
       "groupBy": "select option (optional)",
       "legendFormat": "{{resourceDisplayName}}",
       "metric": "select metric",
       "metricNames": "$resourcegroup",
       "namespace": "$namespace",
       "queryText": "DaysToReachHighUtilization[1d]{resourceMetric =~ \"CPU\", resourceType =~ \"COMANAGED-VM-PDB\"}.avg() ",
       "queryTextRaw": "DaysToReachHighUtilization[1d]{resourceMetric =~ \"CPU\", resourceType =~ \"COMANAGED-VM-PDB\"}.avg() ",
       "region": "$region",
       "resourcegroup": "$resourcegroup",
       "statistic": "select aggregation",
       "tenancy": "DEFAULT/",
       "tenancyName": "DEFAULT/"
      },
      {
       "compartment": "$compartment",
       "compartmentName": "$compartment",
       "groupBy": "select option (optional)",
       "legendFormat": "{{resourceDisplayName}}",
       "metric": "select metric",
       "metricNames": "$resourcegroup",
       "namespace": "$namespace",
       "queryText": "DaysToReachHighUtilization[1d]{resourceMetric =~ \"CPU\", resourceType =~ \"EXTERNAL-NONCDB\"}.avg() ",
       "queryTextRaw": "DaysToReachHighUtilization[1d]{resourceMetric =~ \"CPU\", resourceType =~ \"EXTERNAL-NONCDB\"}.avg() ",
       "region": "$region",
       "resourcegroup": "$resourcegroup",
       "statistic": "select aggregation",
       "tenancy": "DEFAULT/",
       "tenancyName": "DEFAULT/"
      }
     ]
    },
    {
     "title": "Number of DBs to Reaching or Reached Low ${hostResourceMetric:text} Utilisation in the next 30 Days",
     "type": "stat",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "DBs" } },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "compartment": "$compartment",
       "compartmentName": "$compartment",
       "groupBy": "select option (optional)",
       "legendFormat": "{{resourceDisplayName}}",
       "metric": "select metric",
       "metricNames": "$resourcegroup",
       "metricNamesFromNS": "$namespace",
       "namespace": "$namespace",
       "queryText": "DaysToReachLowUtilization[1d]{resourceMetric =~ \"CPU\", resourceType =~ \"EXTERNAL-PDB\"}.avg()  ",
       "queryTextRaw": "DaysToReachLowUtilization[1d]{resourceMetric =~ \"CPU\", resourceType =~ \"EXTERNAL-PDB\"}.avg()  ",
       "region": "$region",
       "resourcegroup": "$resourcegroup",
       "statistic": "select aggregation",
       "tenancy": "DEFAULT/",
       "tenancyName": "DEFAULT/"
      },
      {
       "compartment": "$compartment",
       "compartmentName": "$compartment",
       "groupBy": "select option (optional)",
       "legendFormat": "{{resourceDisplayName}}",
       "metric": "select metric",
       "metricNames": "$resourcegroup",
       "metricNamesFromNS": "$namespace",
       "namespace": "$namespace",
       "queryText": "DaysToReachLowUtilization[1d]{resourceMetric =~ \"CPU\", resourceType =~ \"COMANAGED-VM-PDB\"}.avg() ",
       "queryTextRaw": "DaysToReachLowUtilization[1d]{resourceMetric =~ \"CPU\", resourceType =~ \"COMANAGED-VM-PDB\"}.avg() ",
       "region": "$region",
       "resourcegroup": "$resourcegroup",
       "statistic": "select aggregation",
       "tenancy": "DEFAULT/",
       "tenancyName": "DEFAULT/"
      },
      {
       "compartment": "$compartment",
       "compartmentName": "$compartment",
       "groupBy": "select option (optional)",
       "legendFormat": "{{resourceDisplayName}}",
       "metric": "select metric",
       "metricNames": "$resourcegroup",
       "metricNamesFromNS": "$namespace",
       "namespace": "$namespace",
       "queryText": "DaysToReachLowUtilization[1d]{resourceMetric =~ \"CPU\", resourceType =~ \"EXTERNAL-NONCDB\"}.avg() ",
       "queryTextRaw": "DaysToReachLowUtilization[1d]{resourceMetric =~ \"CPU\", resourceType =~ \"EXTERNAL-NONCDB\"}.avg() ",
       "region": "$region",
       "resourcegroup": "$resourcegroup",
       "statistic": "select aggregation",
       "tenancy": "DEFAULT/",
       "tenancyName": "DEFAULT/"
      }
     ]
    },
    {
     "title": "Top 5 Databases Reaching or Reached Low ${hostResourceMetric:text} Utilisation",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 7, "x": 10, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "d" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "compartment": "$compartment",
       "compartmentName": "$compartment",
       "groupBy": "select option (optional)",
       "legendFormat": "{{resourceDisplayName}}",
       "metric": "select metric",
       "metricNames": "$resourcegroup",
       "metricNamesFromNS": "$namespace",
       "namespace": "$namespace",
       "queryText": "DaysToReachLowUtilization[1d]{resourceMetric =~ \"CPU\", resourceType =~ \"EXTERNAL-PDB\"}.avg() ",
       "queryTextRaw": "DaysToReachLowUtilization[1d]{resourceMetric =~ \"CPU\", resourceType =~ \"EXTERNAL-PDB\"}.avg() ",
       "region": "$region",
       "resourcegroup": "$resourcegroup",
       "statistic": "select aggregation",
       "tenancy": "DEFAULT/",
       "tenancyName": "DEFAULT/"
      },
      {
       "compartment": "$compartment",
       "compartmentName": "$compartment",
       "groupBy": "select option (optional)",
       "legendFormat": "{{resourceDisplayName}}",
       "metric": "select metric",
       "metricNames": "$resourcegroup",
       "metricNamesFromNS": "$namespace",
       "namespace": "$namespace",
       "queryText": "DaysToReachLowUtilization[1d]{resourceMetric =~ \"CPU\", resourceType =~ \"COMANAGED-VM-PDB\"}.avg() ",
       "queryTextRaw": "DaysToReachLowUtilization[1d]{resourceMetric =~ \"CPU\", resourceType =~ \"COMANAGED-VM-PDB\"}.avg() ",
       "region": "$region",
       "resourcegroup": "$resourcegroup",
       "statistic": "select aggregation",
       "tenancy": "DEFAULT/",
       "tenancyName": "DEFAULT/"
      },
      {
       "compartment": "$compartment",
       "compartmentName": "$compartment",
       "groupBy": "select option (optional)",
       "legendFormat": "{{resourceDisplayName}}",
       "metric": "select metric",
       "metricNames": "$resourcegroup",
       "metricNamesFromNS": "$namespace",
       "namespace": "$namespace",
       "queryText": "DaysToReachLowUtilization[1d]{resourceMetric =~ \"CPU\", resourceType =~ \"EXTERNAL-NONCDB\"}.avg() ",
       "queryTextRaw": "DaysToReachLowUtilization[1d]{resourceMetric =~ \"CPU\", resourceType =~ \"EXTERNAL-NONCDB\"}.avg() ",
       "region": "$region",
       "resourcegroup": "$resourcegroup",
       "statistic": "select aggregation",
       "tenancy": "DEFAULT/",
       "tenancyName": "DEFAULT/"
      }
     ]
    },
    {
     "title": "All Databases Reaching or Reached Low ${hostResourceMetric:text} Utilisation",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "d" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "compartment": "$compartment",
       "compartmentName": "$compartment",
       "groupBy": "select option (optional)",
       "legendFormat": "{{resourceDisplayName}}",
       "metric": "select metric",
       "metricNames": "$resourcegroup",
       "namespace": "$namespace",
       "queryText": "DaysToReachLowUtilization[1d]{resourceMetric =~ \"CPU\", resourceType =~ \"EXTERNAL-PDB\"}.avg() ",
       "queryTextRaw": "DaysToReachLowUtilization[1d]{resourceMetric =~ \"CPU\", resourceType =~ \"EXTERNAL-PDB\"}.avg() ",
       "region": "$region",
       "resourcegroup": "$resourcegroup",
       "statistic": "select aggregation",
       "tenancy": "DEFAULT/",
       "tenancyName": "DEFAULT/"
      },
      {
       "compartment": "$compartment",
       "compartmentName": "$compartment",
       "groupBy": "select option (optional)",
       "legendFormat": "{{resourceDisplayName}}",
       "metric": "select metric",
       "metricNames": "$resourcegroup",
       "namespace": "$namespace",
       "queryText": "DaysToReachLowUtilization[1d]{resourceMetric =~ \"CPU\", resourceType =~ \"COMANAGED-VM-PDB\"}.avg() ",
       "queryTextRaw": "DaysToReachLowUtilization[1d]{resourceMetric =~ \"CPU\", resourceType =~ \"COMANAGED-VM-PDB\"}.avg() ",
       "region": "$region",
       "resourcegroup": "$resourcegroup",
       "statistic": "select aggregation",
       "tenancy": "DEFAULT/",
       "tenancyName": "DEFAULT/"
      },
      {
       "compartment": "$compartment",
       "compartmentName": "$compartment",
       "groupBy": "select option (optional)",
       "legendFormat": "{{resourceDisplayName}}",
       "metric": "select metric",
       "metricNames": "$resourcegroup",
       "namespace": "$namespace",
       "queryText": "DaysToReachLowUtilization[1d]{resourceMetric =~ \"CPU\", resourceType =~ \"EXTERNAL-NONCDB\"}.avg() ",
       "queryTextRaw": "DaysToReachLowUtilization[1d]{resourceMetric =~ \"CPU\", resourceType =~ \"EXTERNAL-NONCDB\"}.avg() ",
       "region": "$region",
       "resourcegroup": "$resourcegroup",
       "statistic": "select aggregation",
       "tenancy": "DEFAULT/",
       "tenancyName": "DEFAULT/"
      }
     ]
    }
   ]
  }
 ]
}